# Pipeline for running SDL scans
# https://aka.ms/yaml

trigger:
- master


pool:
  vmImage: 'windows-2019'

steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
    displayName: 'Run PoliCheck'
    inputs:
      targetType: F
      targetArgument: '$(Build.SourcesDirectory)\objects'
    continueOnError: true

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-antimalware.AntiMalware@3
    displayName: 'Run AntiMalware Scan'
    inputs:
      FileDirPath: '$(Build.SourcesDirectory)\objects'
      EnableServices: true
      TreatSignatureUpdateFailureAs: Standard
      TreatStaleSignatureAs: Warning
    continueOnError: true

  - task: PostAnalysis@1
    displayName: "Run SDL Post Analysis"
    inputs:
      AllTools: true
      BinSkimBreakOn: 'Error'
      CodesignValidationBreakOn: 'Error'
      FxCopBreakOn: 'ErrorAbove'
      ModernCopBreakOn: 'Error'
      PoliCheckBreakOn: 'Severity1'
      RoslynAnalyzersBreakOn: 'Error'
      SemmleBreakOn: 'Error'
      TSLintBreakOn: 'Error'
      ToolLogsNotFoundAction: 'Standard'
    continueOnError: false